# Domain types: value objects, enums, errors used by services.

from app.domain.credit_card import CardBucketBalance
from app.domain.currency import (
    SUPPORTED_CURRENCIES,
    get_ars_pair,
    is_supported,
)
from app.domain.cycle_advance import (
    AdvanceResult,
    CycleAdvanceDecision,
    ReverseResult,
    claimed_installment_cuotas,
    claimed_subscription_cycles,
    closest_installment_cuota,
    closest_subscription_cycle,
    installment_link_advanced_cursor,
    subscription_link_advanced_cursor,
)
from app.domain.errors import (
    AccountCardExclusivityError,
    AccountCurrencyChangeBlockedError,
    AccountCurrencyMismatchError,
    AccountReconciliationBeforeLastError,
    AccountReconciliationBeforeOpeningError,
    AccountReconciliationFutureDateError,
    AccountReconciliationNotLatestError,
    CurrencyChangeBlockedError,
    DomainError,
    EmailNotVerifiedError,
    ExchangeRateUnavailableError,
    HasLinkedExpensesError,
    InstallmentLockedFieldError,
    InvalidCredentialsError,
    InvalidImportFileError,
    InvalidInviteError,
    InvalidRefreshTokenError,
    InvalidTokenError,
    InvestmentCurrencyMismatchError,
    InviteEmailTakenError,
    NotFoundError,
    PasswordBreachedError,
    PaymentPairingError,
    PlanRequiredError,
    ReconciliationOwnedEntryError,
    ReconciliationPeriodMismatchError,
)
from app.domain.payment_method import PaymentMethod, ensure_account_pairing, ensure_payment_pairing
from app.domain.payments_calendar import CalendarItem
from app.domain.reconciliation import ensure_not_reconciliation_owned

__all__ = [
    "AccountCardExclusivityError",
    "AccountCurrencyChangeBlockedError",
    "AccountCurrencyMismatchError",
    "AccountReconciliationBeforeLastError",
    "AccountReconciliationBeforeOpeningError",
    "AccountReconciliationFutureDateError",
    "AccountReconciliationNotLatestError",
    "AdvanceResult",
    "CalendarItem",
    "CardBucketBalance",
    "CurrencyChangeBlockedError",
    "CycleAdvanceDecision",
    "DomainError",
    "EmailNotVerifiedError",
    "ExchangeRateUnavailableError",
    "HasLinkedExpensesError",
    "InstallmentLockedFieldError",
    "InvalidCredentialsError",
    "InvalidImportFileError",
    "InvalidInviteError",
    "InvalidRefreshTokenError",
    "InvalidTokenError",
    "InvestmentCurrencyMismatchError",
    "InviteEmailTakenError",
    "NotFoundError",
    "PasswordBreachedError",
    "PaymentMethod",
    "PaymentPairingError",
    "PlanRequiredError",
    "ReconciliationOwnedEntryError",
    "ReconciliationPeriodMismatchError",
    "ReverseResult",
    "SUPPORTED_CURRENCIES",
    "claimed_installment_cuotas",
    "claimed_subscription_cycles",
    "closest_installment_cuota",
    "closest_subscription_cycle",
    "ensure_account_pairing",
    "ensure_not_reconciliation_owned",
    "ensure_payment_pairing",
    "get_ars_pair",
    "installment_link_advanced_cursor",
    "is_supported",
    "subscription_link_advanced_cursor",
]
